add FileController in feature/#11-fileController
nilovs15/nilov_advanced_server pull request #12
Opened 2023-07-18 15:35 UTC by nilovs15

2023-07-19 06:28 UTC, MVlasovD requested changes

2023-07-19 06:28 UTC, MVlasovD commented on src/main/java/com/example/advanced_server/service/impl/FileServiceImpl.java
> +        catch (MalformedURLException e) {
```suggestion
        } catch (MalformedURLException e) {
```

2023-07-19 06:59 UTC, MVlasovD approved these changes

2023-07-19 15:09 UTC, i-kostyakov requested changes

2023-07-19 15:09 UTC, i-kostyakov commented on src/main/java/com/example/advanced_server/controller/NewsController.java
>      public ResponseEntity getUserNews(Authentication authentication,
перенеси authentication на новую строку, и все выравни левее, как у getNews

2023-07-19 15:09 UTC, i-kostyakov commented on src/main/java/com/example/advanced_server/service/impl/FileServiceImpl.java
> +    public static Path uploading;
этого поля быть не должно.

2023-07-20 07:09 UTC, MVlasovD approved these changes

2023-07-20 07:37 UTC, i-kostyakov approved these changes

2023-07-20 07:47 UTC, merged