add Unit tests and migration in feature/#13-AddUnitTestsAndMigration
nilovs15/nilov_advanced_server pull request #15
Opened 2023-07-21 08:10 UTC by nilovs15

2023-07-21 08:40 UTC, MVlasovD requested changes

2023-07-21 08:40 UTC, MVlasovD commented on src/main/java/com/example/advanced_server/service/impl/FileServiceImpl.java
>      @Value("${server.fileUrl}")
а аннотации ты оставил?

2023-07-21 08:40 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/AuthServiceImplTest.java
> +        try {
зачем тебе трай кэтч в тестах использовать, есть специальные ассерты для  проверки выброса исключений и аннотации

2023-07-21 08:40 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/FileServiceTest.java
> +    void success_UploadFile() throws IOException {
```suggestion
    void successUploadFile() throws IOException {
```

2023-07-21 08:40 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/FileServiceTest.java
> +    void success_GetFile() throws IOException {
```suggestion
    void successGetFile() throws IOException {
```

2023-07-21 08:40 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/AuthServiceImplTest.java
> +    void register_Should_Return_Correct_Result() {
```suggestion
    void registerShouldReturnCorrectResult() {
```

2023-07-21 08:40 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/AuthServiceImplTest.java
> +    void login_Should_Return_Correct_Result() {
```suggestion
    void loginShouldReturnCorrectResult() {
```

2023-07-21 08:40 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/NewsServiceImplTest.java
> +    void createNews_Should_Return_Correct_Result() {
!

2023-07-21 08:40 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/NewsServiceImplTest.java
> +    void getNews_Should_Return_Correct_Result() {
!

2023-07-21 08:40 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/UserServiceImplTest.java
> +        }
try/catch в тестах не стоит писать

2023-07-21 09:27 UTC, MVlasovD requested changes

2023-07-21 09:27 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/NewsServiceImplTest.java
> +
нужно негативных сценариев добавить в тестовый класс

2023-07-21 09:27 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/UserServiceImplTest.java
> +    void successDeleteUser( ) {
добавь негативных тестов в класс

2023-07-21 11:49 UTC, MVlasovD approved these changes

2023-07-21 13:04 UTC, i-kostyakov requested changes

2023-07-21 13:04 UTC, i-kostyakov commented on src/main/java/com/example/advanced_server/service/impl/FileServiceImpl.java
> +    private String uploadDir = "/home/dunice/newAfterDelete/files/";
вынести в конфиги окружения.

2023-07-21 13:04 UTC, i-kostyakov commented on src/main/java/com/example/advanced_server/service/impl/FileServiceImpl.java
> +    private String fileUrl = "http://localhost:8080/v1/file/";
вынести в конфиги окружения.

2023-07-21 13:04 UTC, i-kostyakov commented on src/main/java/com/example/advanced_server/dto/BaseSuccessResponse.java
> +                .setStatusCode(1)
что за статускод такой? что он означает?

2023-07-21 13:04 UTC, i-kostyakov commented on src/test/java/com/example/advanced_server/tests/services/AuthServiceImplTest.java
> +        assertNotNull(response.getData().getEmail());
простой проверки на нул мало. нужно проверять что данные такие, какие они должны быть

2023-07-21 13:04 UTC, i-kostyakov commented on src/test/java/com/example/advanced_server/tests/services/NewsServiceImplTest.java
> +        assertTrue(response.getStatusCode().equals(1));
а почему тут не assertEqual

2023-07-21 13:47 UTC, MVlasovD commented on src/main/java/com/example/advanced_server/service/impl/FileServiceImpl.java
> +    private String uploadDir = "/home/dunice/newAfterDelete/files/";
верни @Value, а для тестов добавь эти поля в тестовых классах

2023-07-21 13:48 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/AuthServiceImplTest.java
> +        assertNotNull(response.getData().getEmail());
другие asserts кроме assertNotNull

2023-07-25 10:05 UTC, MVlasovD requested changes

2023-07-25 10:05 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/NewsServiceImplTest.java
> +        assertEquals(response.getData().getContent().get(0).getTitle(), news.getTitle());
чтобы не повторять response.getData().getContent().get(0), можно вынести это в отдельную переменную

2023-07-25 10:05 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/NewsServiceImplTest.java
> +        assertEquals(response.getData().getContent().get(0).getTitle(), news.getTitle());
тоже самое

2023-07-25 10:05 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/UserServiceImplTest.java
> +        assertNotNull(response.getData().get(0).getId());
и тут тоже

2023-07-25 11:52 UTC, MVlasovD requested changes

2023-07-25 11:52 UTC, MVlasovD commented on src/test/java/com/example/advanced_server/tests/services/NewsServiceImplTest.java
> +        Pageable pageable = PageRequest.of(0, 3);
все-таки избавься во всех тестах от магических чисел

2023-07-25 12:10 UTC, MVlasovD approved these changes

2023-07-26 14:01 UTC, i-kostyakov approved these changes

2023-07-26 15:51 UTC, merged